// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhggmektzypvfiijspnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoZ2dtZWt0enlwdmZpaWpzcG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1Nzk4ODUsImV4cCI6MjA1NjE1NTg4NX0.bRQL6ihCJxUgwDpK6H6LkqGjJeHrSyQ-nRbmxRnalnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);